version: '3.8'

services:
  broken_auth_lab:
    build: .
    container_name: broken_auth_lab
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 