services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 6 pygoat.wsgi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - migration
  migration:
    image: pygoat/pygoat:latest
    command: python manage.py migrate --noinput
    volumes:
      - .:/app