apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aerie-dev
  name: aerie-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerie-workspace
  template:
    metadata:
      name: aerie-workspace
      labels:
        app: aerie-workspace
    spec:
      containers:
        - name: aerie-workspace
          image: ghcr.io/nasa-ammos/aerie-workspace:develop
          ports:
            - containerPort: 28000
          volumeMounts:
            - mountPath: /usr/src/ws
              name: workspace_file_store
          env:
            - name: JAVA_OPTS
              value: |
                -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO -Dorg.slf4j.simpleLogger.logFile=System.err
            - name: AERIE_DB_HOST
              value: postgres
            - name: AERIE_DB_PORT
              value: "5432"
            - name: SEQUENCING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: SEQUENCING_USERNAME
            - name: SEQUENCING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: SEQUENCING_PASSWORD
            - name: WORKSPACE_STORE
              value: /usr/src/ws
            - name: WORKSPACE_PORT
              value: "28000"
            - name: HASURA_GRAPHQL_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: HASURA_GRAPHQL_JWT_SECRET
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: HASURA_GRAPHQL_ADMIN_SECRET
      restartPolicy: Always
      volumes:
        - name: workspace_file_store
          persistentVolumeClaim:
            claimName: workspace_file_store
