apiVersion: v1
kind: Service
metadata:
  namespace: aerie-dev
  name: aerie-workspace
spec:
  selector:
    app: aerie-workspace
  ports:
    - name: "28000"
      port: 28000
      targetPort: 28000

