apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aerie-dev
  name: aerie-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerie-gateway
  template:
    metadata:
      labels:
        app: aerie-gateway
    spec:
      containers:
        - name: aerie-gateway
          image: ghcr.io/nasa-ammos/aerie-gateway:develop
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /app/files
              name: aerie-file-store
          env:
            - name: AUTH_TYPE
              value: none
            - name: GQL_API_URL
              value: http://localhost:8080/v1/graphql
            - name: HASURA_GRAPHQL_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: HASURA_GRAPHQL_JWT_SECRET
            - name: LOG_FILE
              value: console
            - name: LOG_LEVEL
              value: warn
            - name: PORT
              value: "9000"
            - name: AERIE_DB_HOST
              value: postgres
            - name: AERIE_DB_PORT
              value: "5432"
            - name: GATEWAY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: GATEWAY_USERNAME
            - name: GATEWAY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: GATEWAY_PASSWORD
      volumes:
        - name: aerie-file-store
          persistentVolumeClaim:
            claimName: aerie-file-store
