# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Bandit is a security linter designed to find common security issues in Python code.
# This action will run Bandit on your codebase.
# The results of the scan will be found under the Security tab of your repository.

# https://github.com/marketplace/actions/bandit-scan is ISC licensed, by abirismyname
# https://pypi.org/project/bandit/ is Apache v2.0 licensed, by PyCQA

name: Bandit
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '37 14 * * 1'

jobs:
  bandit:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Bandit (with SARIF support)
        run: pip install 'bandit[sarif]'

      - name: Run Bandit (deep/verbose scan with CWE + SARIF)
        run: |
          bandit -r .  --severity-level=low -n 5 -f sarif -o bandit.sarif
          # bandit -r . \
          #   --severity-level=low \
          #   --confidence-level=low \
          #   -n 5 \
          #   -f sarif -o bandit.sarif
          # Optional extra artifact:
	  # bandit -r . --severity-level=low --confidence-level=low -f json -o bandit.json
        # continue-on-error: true  # keep CI green; use exit-zero equivalent

      - name: Upload SARIF to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif
