# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '42 23 * * 2'

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DevSkim scanner (thorough + CWE-ready)
        uses: microsoft/DevSkim-Action@v1
        with:
          # Scan the whole repo (default) and also peek inside archives
          directory-to-scan: .
          should-scan-archives: true
          # Make sure the output file is where the next step expects it
          output-filename: devskim-results.sarif
          # Pass extra CLI options to broaden checks & include lower-confidence results
          extra-options: >
            --confidence High,Medium,Low
            --severity Critical,Important,Moderate,BestPractice,ManualReview

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: devskim-results.sarif
          wait-for-processing: false
          # Optional but helpful if you ever upload multiple SARIF files for the same commit
          category: devskim


