name: gitleaks
on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # run once a day at 4 AM

jobs:
  scan:
    name: gitleaks (CLI)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # required to upload SARIF
      actions: read            # helps avoid SARIF upload perms edge-cases
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for full-history scans

      # Ensure all branches/tags are present so --log-opts="--all ..." actually scans everything
      - name: Fetch all refs
        run: |
          git fetch --all --tags --prune

      - name: Gitleaks (git history → SARIF)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            ghcr.io/gitleaks/gitleaks:latest \
              git \
                  --report-format sarif \
                  --report-path /repo/gitleaks-history.sarif \
                  --log-opts="--all --full-history" \
                  --redact \
                  --verbose \
                  --max-archive-depth 3 \
                  --max-decode-depth 3

      - name: Gitleaks (working tree → SARIF)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            ghcr.io/gitleaks/gitleaks:latest \
              dir  \
                  --report-format sarif \
                  --report-path /repo/gitleaks-workspace.sarif \
                  --redact \
                  --verbose \
                  --max-archive-depth 3 \
                  --max-decode-depth 3

      - name: Upload SARIF (history)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-history.sarif

      - name: Upload SARIF (workspace)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-workspace.sarif
