name: Infer Static Analysis - Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  infer-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java (for Infer)
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install Infer
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip build-essential m4
          wget https://github.com/facebook/infer/releases/download/v1.2.0/infer-linux-x86_64-v1.2.0.tar.xz
          tar -xf https://github.com/facebook/infer/releases/download/v1.2.0/infer-linux-x86_64-v1.2.0.tar.xz
          echo "$PWD/infer-linux64-v1.2.0/bin" >> $GITHUB_PATH

      - name: Run Infer and emit SARIF
        run: |
          # Build your project via the usual command after `infer run --`
          infer run --sarif -- make
          test -f infer-out/report.sarif || (echo "SARIF not found in infer-out/"; ls -R infer-out || true; exit 1)
          cp infer-out/report.sarif infer-out/infer-code.sarif

      - name: Upload SARIF to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: infer-out/infer-code.sarif
