name: Infer Static Analysis - Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  infer-analysis:
    runs-on: ubuntu-latest

    env:
      INFER_VERSION: v1.2.0
      INFER_BASENAME: infer-linux-x86_64-v1.2.0
      INFER_INSTALL_DIR: ${{ github.workspace }}/.tools/infer/infer-linux-x86_64-v1.2.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (for Infer)
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Infer ${{ env.INFER_VERSION }}
        id: infer-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.INFER_INSTALL_DIR }}
          key: infer-${{ runner.os }}-${{ env.INFER_BASENAME }}-v1

      - name: Install Infer (if cache miss)
        if: steps.infer-cache.outputs.cache-hit != 'true'
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y wget xz-utils build-essential m4
          mkdir -p "$(dirname "${INFER_INSTALL_DIR}")"
          wget "https://github.com/facebook/infer/releases/download/${INFER_VERSION}/${INFER_BASENAME}.tar.xz"
          tar -xf "${INFER_BASENAME}.tar.xz"
          # Move the extracted folder into the cached install dir
          mv "${INFER_BASENAME}" "${INFER_INSTALL_DIR}"

      - name: Add Infer to PATH and verify
        run: |
          set -euxo pipefail
          echo "${INFER_INSTALL_DIR}/bin" >> "$GITHUB_PATH"
          export PATH="${INFER_INSTALL_DIR}/bin:$PATH"
          infer --version

      - name: Run Infer and emit SARIF
        # Build your project via the usual command after `infer run --`
          infer run --sarif -- make --keep-going
          test -f infer-out/report.sarif || (echo "SARIF not found in infer-out/"; ls -R infer-out || true; exit 1)
          cp infer-out/report.sarif infer-out/infer-code.sarif

      - name: Upload SARIF to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: infer-out/infer-code.sarif
