on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: 16 6 * * *

name: Semgrep

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- Official Semgrep Action ----------
      - name: Run Semgrep (with extended security configs & SARIF)
        uses: returntocorp/semgrep-action@v1
        with:
          args: >-
            --sarif --output=semgrep.sarif
            --config auto
            --config p/owasp-top-ten
            --config p/cwe-top-25
            --config p/security-audit
            --config p/secrets
            --timeout=30 --timeout-threshold=0 --max-target-bytes=0
            --metrics=off

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
