on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: 16 6 * * *

name: Semgrep

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep (broader rules; deeper scan; SARIF)
        run: |
          semgrep scan \
            --config auto \
            --config p/owasp-top-ten \
            --config p/cwe-top-25 \
            --config p/security-audit \
            --config p/secrets \
            --timeout=30 \
            --timeout-threshold=0 \
            --max-target-bytes=0 \
            --metrics=off \
            --sarif-output=semgrep.sarif
      # --timeout/--timeout-threshold reduce skipped work; --max-target-bytes=0 avoids skipping large files.
      # --sarif-output writes a SARIF file that GitHub can ingest. :contentReference[oaicite:8]{index=8}

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
