on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: 16 6 * * *

name: Semgrep

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      # “Deeper” scan knob (in seconds) – increases per-rule/file allowance
      SEMGREP_TIMEOUT: "30"   # raise if you still see timeouts  :contentReference[oaicite:2]{index=2}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----- Official (legacy) Semgrep Action: uses inputs, not args -----
      - name: Run Semgrep (extended rulepacks; SARIF)
        uses: returntocorp/semgrep-action@v1
        with:
          # Multiple rulepacks for broader security coverage
          config: >-
            auto
            p/owasp-top-ten
            p/cwe-top-25
            p/security-audit
            p/secrets
          generateSarif: "1"     # writes semgrep.sarif by default  :contentReference[oaicite:3]{index=3}

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
