- name: Checkout
  uses: actions/checkout@master
  with:
    lfs: true                # if you use LFS (safe to leave on)
    submodules: recursive    # if you use submodules

- name: Set up Snyk CLI
  uses: snyk/actions/setup@v1
  with:
    snyk-version: latest

- name: Sanity check workspace
  run: |
    echo "PWD=$(pwd)"
    echo "--- top-level files ---"
    ls -la
    find . -maxdepth 1 -type f -name '*.c' -o -name '*.cpp' -o -name '*.m' -o -name '*.java' | sed -n '1,50p'
    snyk code test "$PWD/main2.c" --sarif-file-output=snyk-code.sarif


# Snyk Code (SAST) — make sure we point at the repo root (.)
- name: Snyk Code (SAST) — SARIF
  continue-on-error: true
  run: |
    snyk code test . \
      --sarif-file-output=snyk-code.sarif \
      --severity-threshold=medium \
      --log-level=trace --debug    # keep while diagnosing

- name: Upload Snyk Code SARIF
  if: always()
  uses: github/codeql-action/upload-sarif@v3
  with:
    sarif_file: snyk-code.sarif
    category: snyk-code
