name: Snyk Security (SAST + SCA + Container + IaC w/ SARIF)

#Prereqs
# * Add a repo secret SNYK_TOKEN.
# * If you want container scanning, include a Dockerfile.
# * Adjust paths (e.g., src/, infra/) as needed.

on:
  pull_request:
  push:
    branches: [ main, master ]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read
  security-events: write   # needed to upload SARIF

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: |
          curl -sL https://snyk.io/install | bash
          snyk --version

      ############################################################
      # SAST — Snyk Code (multi-language; CWEs included in SARIF
      # when rules provide them). Strengthened settings below.
      ############################################################
      - name: Snyk Code (SAST) — SARIF
        continue-on-error: true
        run: |
          # Scan entire repo. Narrow to a folder if needed for speed (e.g., "./src").
          # Hardening ideas:
          #  - Raise the bar: --severity-threshold=high
          #  - Include ignored (for audits): add --include-ignores
          #  - Exclude generated dirs: add --exclude=node_modules,dist,build
          snyk code test \
            --severity-threshold=medium \
            --sarif-file-output=snyk-code.sarif

      - name: Upload Snyk Code SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
          category: snyk-code

      ############################################################
      # Open Source / SCA — polyglot dependency scanning
      ############################################################
      - name: Snyk Open Source (SCA) — SARIF
        continue-on-error: true
        run: |
          # Detects manifests across the repo (pom.xml, package.json, Pipfile/reqs,
          # go.mod, Gemfile, Cargo.toml, etc.). Increase detection-depth as needed.
          snyk test \
            --all-projects \
            --detection-depth=6 \
            --severity-threshold=high \
            --sarif-file-output=snyk-oss.sarif

      - name: Upload Snyk OSS SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-oss.sarif
          category: snyk-oss

      - name: Snyk OSS (monitor baseline in Snyk UI)
        if: ${{ github.event_name != 'pull_request' }}
        run: snyk monitor --all-projects --detection-depth=6

      ############################################################
      # Container — image vuln scan (OS + app packages)
      ############################################################
      - name: Build image
        run: docker build -t local/app:${{ github.sha }} .

      - name: Snyk Container — SARIF
        continue-on-error: true
        run: |
          snyk container test local/app:${{ github.sha }} \
            --file=Dockerfile \
            --severity-threshold=high \
            --sarif-file-output=snyk-container.sarif

      - name: Upload Snyk Container SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-container.sarif
          category: snyk-container

      - name: Snyk Container (monitor baseline)
        if: ${{ github.event_name != 'pull_request' }}
        run: snyk container monitor local/app:${{ github.sha }} --file=Dockerfile

      ############################################################
      # IaC — Terraform / Kubernetes / CloudFormation / ARM / etc.
      ############################################################
      - name: Snyk IaC — SARIF
        continue-on-error: true
        env:
          IAC_DIR: .
        run: |
          # Add --report for Snyk UI reporting; SARIF goes to GitHub code scanning.
          snyk iac test "$IAC_DIR" \
            --severity-threshold=medium \
            --sarif-file-output=snyk-iac.sarif

      - name: Upload Snyk IaC SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-iac.sarif
          category: snyk-iac

      ############################################################
      # Final "gate": fail the job if HIGH-severity issues remain
      # (tune threshold to your risk tolerance)
      ############################################################
      - name: Enforce failure on HIGH across scanners
        if: ${{ success() }}
        run: |
          set -e
          snyk code test --severity-threshold=high
          snyk test --all-projects --severity-threshold=high
          snyk container test local/app:${{ github.sha }} --file=Dockerfile --severity-threshold=high
          snyk iac test . --severity-threshold=high
